busca:
	gcc busca_multithread.c -o busca_multithread.o -lpthread

aritmetica:
	gcc media_artimetica.c matriz.c -o media_artimetica.o

geometrica:
	gcc media_geometrica.c matriz.c -o media_geometrica.o
