busca:
	gcc busca_multithread.c -o busca_multithread.o -lpthread

aritmetica:
	gcc media_aritmetica.c matriz.c -o media_aritmetica.o

geometrica:
	gcc media_geometrica.c matriz.c -lm -o media_geometrica.o